package sources

// WordEntry is a single vocabulary entry in the embedded German word list.
type WordEntry struct {
	German  string
	Turkish string
	English string
}

// GermanWords is the embedded list of common German words (A1-B1 level).
var GermanWords = []WordEntry{
	// Numbers
	{"eins", "bir", "one"},
	{"zwei", "iki", "two"},
	{"drei", "üç", "three"},
	{"vier", "dört", "four"},
	{"fünf", "beş", "five"},
	{"sechs", "altı", "six"},
	{"sieben", "yedi", "seven"},
	{"acht", "sekiz", "eight"},
	{"neun", "dokuz", "nine"},
	{"zehn", "on", "ten"},
	{"zwanzig", "yirmi", "twenty"},
	{"hundert", "yüz", "hundred"},
	// Greetings
	{"Hallo", "Merhaba", "Hello"},
	{"Guten Morgen", "Günaydın", "Good morning"},
	{"Guten Tag", "İyi günler", "Good day"},
	{"Guten Abend", "İyi akşamlar", "Good evening"},
	{"Auf Wiedersehen", "Hoşça kal", "Goodbye"},
	{"Tschüss", "Görüşürüz", "Bye"},
	{"Bitte", "Lütfen / Rica ederim", "Please / You're welcome"},
	{"Danke", "Teşekkür ederim", "Thank you"},
	{"Entschuldigung", "Özür dilerim", "Excuse me / Sorry"},
	{"Ja", "Evet", "Yes"},
	{"Nein", "Hayır", "No"},
	{"Vielleicht", "Belki", "Maybe"},
	// Pronouns
	{"ich", "ben", "I"},
	{"du", "sen", "you (informal)"},
	{"er", "o (erkek)", "he"},
	{"sie", "o (kadın)", "she"},
	{"es", "o (nesne)", "it"},
	{"wir", "biz", "we"},
	{"ihr", "siz (informal)", "you all"},
	{"Sie", "siz (resmi)", "you (formal)"},
	// Common verbs
	{"sein", "olmak", "to be"},
	{"haben", "sahip olmak", "to have"},
	{"machen", "yapmak", "to do / make"},
	{"gehen", "gitmek", "to go"},
	{"kommen", "gelmek", "to come"},
	{"sehen", "görmek", "to see"},
	{"geben", "vermek", "to give"},
	{"nehmen", "almak", "to take"},
	{"sagen", "söylemek", "to say"},
	{"sprechen", "konuşmak", "to speak"},
	{"schreiben", "yazmak", "to write"},
	{"lesen", "okumak", "to read"},
	{"hören", "duymak / dinlemek", "to hear / listen"},
	{"essen", "yemek", "to eat"},
	{"trinken", "içmek", "to drink"},
	{"schlafen", "uyumak", "to sleep"},
	{"kaufen", "satın almak", "to buy"},
	{"verkaufen", "satmak", "to sell"},
	{"fahren", "sürmek / gitmek", "to drive / travel"},
	{"fliegen", "uçmak", "to fly"},
	{"laufen", "koşmak / yürümek", "to run / walk"},
	{"arbeiten", "çalışmak", "to work"},
	{"lernen", "öğrenmek", "to learn"},
	{"wissen", "bilmek", "to know (fact)"},
	{"kennen", "tanımak", "to know (person)"},
	{"denken", "düşünmek", "to think"},
	{"wohnen", "oturmak / yaşamak", "to live (reside)"},
	{"heißen", "adı olmak", "to be named"},
	{"verstehen", "anlamak", "to understand"},
	{"helfen", "yardım etmek", "to help"},
	{"fragen", "sormak", "to ask"},
	{"antworten", "cevap vermek", "to answer"},
	{"öffnen", "açmak", "to open"},
	{"schließen", "kapatmak", "to close"},
	{"warten", "beklemek", "to wait"},
	{"suchen", "aramak", "to search"},
	{"finden", "bulmak", "to find"},
	{"brauchen", "ihtiyacı olmak", "to need"},
	{"mögen", "sevmek", "to like"},
	{"lieben", "aşık olmak / sevmek", "to love"},
	{"zahlen", "ödemek", "to pay"},
	{"spielen", "oynamak", "to play"},
	{"zeigen", "göstermek", "to show"},
	{"bleiben", "kalmak", "to stay"},
	{"bringen", "getirmek", "to bring"},
	{"stehen", "durmak / ayakta olmak", "to stand"},
	{"sitzen", "oturmak", "to sit"},
	{"liegen", "yatmak / uzanmak", "to lie (down)"},
	{"beginnen", "başlamak", "to begin"},
	{"enden", "bitmek", "to end"},
	// Nouns — people
	{"der Mann", "adam / erkek", "man"},
	{"die Frau", "kadın", "woman"},
	{"das Kind", "çocuk", "child"},
	{"der Freund", "erkek arkadaş / dost", "friend (male)"},
	{"die Freundin", "kız arkadaş / dost", "friend (female)"},
	{"die Familie", "aile", "family"},
	{"die Mutter", "anne", "mother"},
	{"der Vater", "baba", "father"},
	{"die Schwester", "kız kardeş", "sister"},
	{"der Bruder", "erkek kardeş", "brother"},
	{"die Eltern", "ebeveynler", "parents"},
	{"der Sohn", "oğul", "son"},
	{"die Tochter", "kız", "daughter"},
	{"der Chef", "patron / şef", "boss"},
	{"der Kollege", "meslektaş", "colleague"},
	// Nouns — home
	{"das Haus", "ev", "house"},
	{"die Wohnung", "daire", "apartment"},
	{"das Zimmer", "oda", "room"},
	{"die Küche", "mutfak", "kitchen"},
	{"das Bad", "banyo", "bathroom"},
	{"der Tisch", "masa", "table"},
	{"der Stuhl", "sandalye", "chair"},
	{"das Bett", "yatak", "bed"},
	{"die Tür", "kapı", "door"},
	{"das Fenster", "pencere", "window"},
	{"die Treppe", "merdiven", "stairs"},
	// Nouns — city / transport
	{"die Straße", "cadde / sokak", "street"},
	{"die Stadt", "şehir", "city"},
	{"das Land", "ülke / kırsal", "country / countryside"},
	{"der Weg", "yol", "way / path"},
	{"der Zug", "tren", "train"},
	{"das Auto", "araba", "car"},
	{"das Flugzeug", "uçak", "airplane"},
	{"der Bus", "otobüs", "bus"},
	{"das Fahrrad", "bisiklet", "bicycle"},
	{"der Bahnhof", "tren istasyonu", "train station"},
	{"der Flughafen", "havalimanı", "airport"},
	{"die Haltestelle", "durak", "bus stop"},
	{"das Ticket", "bilet", "ticket"},
	{"die Fahrt", "yolculuk / sürüş", "journey / ride"},
	// Nouns — time
	{"die Zeit", "zaman", "time"},
	{"der Tag", "gün", "day"},
	{"die Nacht", "gece", "night"},
	{"die Woche", "hafta", "week"},
	{"der Monat", "ay", "month"},
	{"das Jahr", "yıl", "year"},
	{"die Stunde", "saat", "hour"},
	{"die Minute", "dakika", "minute"},
	{"die Sekunde", "saniye", "second"},
	{"der Morgen", "sabah", "morning"},
	{"der Abend", "akşam", "evening"},
	// Nouns — work / school
	{"die Schule", "okul", "school"},
	{"die Arbeit", "iş", "work"},
	{"das Büro", "ofis", "office"},
	{"die Sprache", "dil", "language"},
	{"das Deutsch", "Almanca", "German"},
	{"der Unterricht", "ders", "lesson / class"},
	{"der Lehrer", "öğretmen", "teacher"},
	{"der Schüler", "öğrenci", "student (school)"},
	{"der Student", "üniversite öğrencisi", "university student"},
	{"das Buch", "kitap", "book"},
	{"das Heft", "defter", "notebook"},
	{"der Stift", "kalem", "pen / pencil"},
	// Nouns — food
	{"das Wasser", "su", "water"},
	{"das Essen", "yemek", "food / meal"},
	{"das Brot", "ekmek", "bread"},
	{"die Milch", "süt", "milk"},
	{"der Kaffee", "kahve", "coffee"},
	{"der Tee", "çay", "tea"},
	{"der Apfel", "elma", "apple"},
	{"die Banane", "muz", "banana"},
	{"die Tomate", "domates", "tomato"},
	{"das Fleisch", "et", "meat"},
	{"der Fisch", "balık", "fish"},
	{"das Ei", "yumurta", "egg"},
	{"der Käse", "peynir", "cheese"},
	{"die Butter", "tereyağı", "butter"},
	{"der Zucker", "şeker", "sugar"},
	{"das Salz", "tuz", "salt"},
	{"der Kuchen", "kek / pasta", "cake"},
	// Nouns — nature
	{"die Sonne", "güneş", "sun"},
	{"der Mond", "ay", "moon"},
	{"der Stern", "yıldız", "star"},
	{"der Regen", "yağmur", "rain"},
	{"der Schnee", "kar", "snow"},
	{"der Wind", "rüzgar", "wind"},
	{"das Feuer", "ateş", "fire"},
	{"der Baum", "ağaç", "tree"},
	{"die Blume", "çiçek", "flower"},
	{"das Tier", "hayvan", "animal"},
	{"der Hund", "köpek", "dog"},
	{"die Katze", "kedi", "cat"},
	{"der Vogel", "kuş", "bird"},
	// Nouns — body
	{"der Kopf", "baş", "head"},
	{"das Auge", "göz", "eye"},
	{"das Ohr", "kulak", "ear"},
	{"die Nase", "burun", "nose"},
	{"der Mund", "ağız", "mouth"},
	{"die Hand", "el", "hand"},
	{"der Fuß", "ayak", "foot"},
	{"das Herz", "kalp", "heart"},
	{"der Rücken", "sırt", "back"},
	// Nouns — health
	{"der Arzt", "doktor", "doctor"},
	{"das Krankenhaus", "hastane", "hospital"},
	{"die Medizin", "ilaç", "medicine"},
	{"der Schmerz", "ağrı", "pain"},
	{"die Tablette", "hap / tablet", "pill / tablet"},
	// Nouns — money / shopping
	{"das Geld", "para", "money"},
	{"der Supermarkt", "süpermarket", "supermarket"},
	{"der Preis", "fiyat", "price"},
	{"die Rechnung", "fatura / hesap", "bill / invoice"},
	{"das Angebot", "teklif / indirim", "offer / discount"},
	// Nouns — technology
	{"das Handy", "cep telefonu", "mobile phone"},
	{"der Computer", "bilgisayar", "computer"},
	{"das Internet", "internet", "internet"},
	{"die E-Mail", "e-posta", "email"},
	{"das Passwort", "şifre", "password"},
	{"die App", "uygulama", "app"},
	// Nouns — emotions / abstract
	{"die Angst", "korku", "fear"},
	{"die Freude", "sevinç", "joy"},
	{"die Liebe", "aşk / sevgi", "love"},
	{"der Hass", "nefret", "hate"},
	{"die Hoffnung", "umut", "hope"},
	{"die Trauer", "üzüntü", "sadness"},
	{"das Glück", "mutluluk / şans", "happiness / luck"},
	{"die Wahrheit", "gerçek / doğru", "truth"},
	{"die Lüge", "yalan", "lie"},
	{"die Freiheit", "özgürlük", "freedom"},
	{"die Gerechtigkeit", "adalet", "justice"},
	{"die Verantwortung", "sorumluluk", "responsibility"},
	{"das Vertrauen", "güven", "trust"},
	{"der Respekt", "saygı", "respect"},
	{"die Geduld", "sabır", "patience"},
	{"der Mut", "cesaret", "courage"},
	{"die Kraft", "güç", "strength / power"},
	{"der Erfolg", "başarı", "success"},
	{"das Problem", "sorun", "problem"},
	{"die Lösung", "çözüm", "solution"},
	{"die Chance", "fırsat", "chance / opportunity"},
	{"der Unterschied", "fark", "difference"},
	{"das Beispiel", "örnek", "example"},
	{"die Frage", "soru", "question"},
	{"die Antwort", "cevap", "answer"},
	{"der Grund", "neden / sebep", "reason"},
	{"das Ziel", "hedef / amaç", "goal / aim"},
	{"die Idee", "fikir", "idea"},
	{"die Meinung", "görüş / fikir", "opinion"},
	// Adjectives
	{"groß", "büyük", "big"},
	{"klein", "küçük", "small"},
	{"gut", "iyi", "good"},
	{"schlecht", "kötü", "bad"},
	{"neu", "yeni", "new"},
	{"alt", "eski / yaşlı", "old"},
	{"jung", "genç", "young"},
	{"schnell", "hızlı", "fast"},
	{"langsam", "yavaş", "slow"},
	{"schön", "güzel", "beautiful"},
	{"hässlich", "çirkin", "ugly"},
	{"warm", "sıcak", "warm"},
	{"kalt", "soğuk", "cold"},
	{"heiß", "çok sıcak", "hot"},
	{"laut", "gürültülü", "loud"},
	{"leise", "sessiz", "quiet"},
	{"schwer", "ağır / zor", "heavy / difficult"},
	{"leicht", "hafif / kolay", "light / easy"},
	{"viel", "çok", "much / many"},
	{"wenig", "az", "few / little"},
	{"richtig", "doğru", "correct"},
	{"falsch", "yanlış", "wrong"},
	{"offen", "açık", "open"},
	{"geschlossen", "kapalı", "closed"},
	{"müde", "yorgun", "tired"},
	{"krank", "hasta", "sick"},
	{"gesund", "sağlıklı", "healthy"},
	{"hungrig", "aç", "hungry"},
	{"glücklich", "mutlu", "happy"},
	{"traurig", "üzgün", "sad"},
	{"wichtig", "önemli", "important"},
	{"interessant", "ilginç", "interesting"},
	{"langweilig", "sıkıcı", "boring"},
	{"schwierig", "zor", "difficult"},
	{"einfach", "kolay / basit", "easy / simple"},
	{"teuer", "pahalı", "expensive"},
	{"billig", "ucuz", "cheap"},
	{"sicher", "güvenli / emin", "safe / sure"},
	{"gefährlich", "tehlikeli", "dangerous"},
	// Prepositions
	{"mit", "ile / birlikte", "with"},
	{"ohne", "olmadan", "without"},
	{"für", "için", "for"},
	{"gegen", "karşı", "against"},
	{"durch", "aracılığıyla / ile", "through / by"},
	{"über", "hakkında / üzerinde", "about / over"},
	{"unter", "altında", "under"},
	{"neben", "yanında", "next to"},
	{"zwischen", "arasında", "between"},
	{"vor", "önünde / önce", "in front of / before"},
	{"nach", "sonra / göre", "after / according to"},
	{"seit", "beri", "since / for"},
	{"bis", "kadar", "until"},
	{"von", "den / dan / -ın", "from / of"},
	{"zu", "e / a / -e doğru", "to / at"},
	{"an", "da / de / yanında", "at / on"},
	{"auf", "üstünde", "on top of"},
	{"in", "içinde", "in"},
	{"aus", "dan / den / içinden", "out of / from"},
	// Question words
	{"was", "ne", "what"},
	{"wer", "kim", "who"},
	{"wo", "nerede", "where"},
	{"wann", "ne zaman", "when"},
	{"warum", "neden / niçin", "why"},
	{"wie", "nasıl", "how"},
	{"wie viel", "ne kadar", "how much"},
	{"welcher", "hangi", "which"},
	{"wohin", "nereye", "where to"},
	{"woher", "nereden", "where from"},
	// Colors
	{"rot", "kırmızı", "red"},
	{"blau", "mavi", "blue"},
	{"grün", "yeşil", "green"},
	{"gelb", "sarı", "yellow"},
	{"schwarz", "siyah", "black"},
	{"weiß", "beyaz", "white"},
	{"grau", "gri", "gray"},
	{"braun", "kahverengi", "brown"},
	{"orange", "turuncu", "orange"},
	{"lila", "mor", "purple"},
	{"rosa", "pembe", "pink"},
	// Time adverbs
	{"heute", "bugün", "today"},
	{"gestern", "dün", "yesterday"},
	{"morgen", "yarın", "tomorrow"},
	{"jetzt", "şimdi", "now"},
	{"dann", "sonra", "then"},
	{"immer", "her zaman", "always"},
	{"nie", "asla / hiç", "never"},
	{"manchmal", "bazen", "sometimes"},
	{"oft", "sık sık", "often"},
	{"schon", "zaten / artık", "already / yet"},
	{"noch", "hâlâ / daha", "still / yet"},
	{"früh", "erken", "early"},
	{"spät", "geç", "late"},
	// Place adverbs / connectors
	{"hier", "burada", "here"},
	{"dort", "orada", "there"},
	{"auch", "da / de / ayrıca", "also / too"},
	{"aber", "ama / fakat", "but"},
	{"weil", "çünkü", "because"},
	{"wenn", "eğer / ne zaman", "if / when"},
	{"dass", "ki", "that (conjunction)"},
	{"oder", "ya da / veya", "or"},
	{"und", "ve", "and"},
	{"sehr", "çok", "very"},
	{"so", "öyle / böyle", "so / such"},
	{"mehr", "daha fazla", "more"},
	{"weniger", "daha az", "less"},
	{"alle", "hepsi / tüm", "all / everyone"},
	{"jeder", "her / herkes", "every / everyone"},
	{"viele", "birçok", "many"},
	{"einige", "bazı", "some"},
	{"kein", "hiç / hiçbir", "no / none"},
	{"etwas", "bir şey / biraz", "something / some"},
	{"alles", "her şey", "everything"},
	{"nichts", "hiçbir şey", "nothing"},
	{"jemand", "biri / birisi", "someone"},
	{"niemand", "hiç kimse", "nobody"},
}
