#pragma once
#include <Arduino.h>

// Embedded data for the disconnect-splash cycle.
// drawDisconnectSplash() cycles through 4 phases (5 s each):
//   0 = spinner (original)      1 = today's Pokemon name + types
//   2 = German word big         3 = German word small + English meaning
//
// "Today" is approximated from millis() — no RTC on the MCU, so the content
// rotates by session rather than calendar day.  The host app shows the true
// calendar-day item once connected.

struct SplashPokemon {
    const char* name;
    const char* type1;
    const char* type2; // "" for single-type
};

struct SplashGerman {
    const char* german;  // ASCII-folded (ä→a, ö→o, ü→u, ß→ss)
    const char* english;
};

// All 151 Gen 1 Pokémon in Pokédex order (IDs 1–151).
static const SplashPokemon POKEMON[] = {
    {"Bulbasaur",   "Grass",    "Poison"},
    {"Ivysaur",     "Grass",    "Poison"},
    {"Venusaur",    "Grass",    "Poison"},
    {"Charmander",  "Fire",     ""},
    {"Charmeleon",  "Fire",     ""},
    {"Charizard",   "Fire",     "Flying"},
    {"Squirtle",    "Water",    ""},
    {"Wartortle",   "Water",    ""},
    {"Blastoise",   "Water",    ""},
    {"Caterpie",    "Bug",      ""},
    {"Metapod",     "Bug",      ""},
    {"Butterfree",  "Bug",      "Flying"},
    {"Weedle",      "Bug",      "Poison"},
    {"Kakuna",      "Bug",      "Poison"},
    {"Beedrill",    "Bug",      "Poison"},
    {"Pidgey",      "Normal",   "Flying"},
    {"Pidgeotto",   "Normal",   "Flying"},
    {"Pidgeot",     "Normal",   "Flying"},
    {"Rattata",     "Normal",   ""},
    {"Raticate",    "Normal",   ""},
    {"Spearow",     "Normal",   "Flying"},
    {"Fearow",      "Normal",   "Flying"},
    {"Ekans",       "Poison",   ""},
    {"Arbok",       "Poison",   ""},
    {"Pikachu",     "Electric", ""},
    {"Raichu",      "Electric", ""},
    {"Sandshrew",   "Ground",   ""},
    {"Sandslash",   "Ground",   ""},
    {"Nidoran-F",   "Poison",   ""},
    {"Nidorina",    "Poison",   ""},
    {"Nidoqueen",   "Poison",   "Ground"},
    {"Nidoran-M",   "Poison",   ""},
    {"Nidorino",    "Poison",   ""},
    {"Nidoking",    "Poison",   "Ground"},
    {"Clefairy",    "Fairy",    ""},
    {"Clefable",    "Fairy",    ""},
    {"Vulpix",      "Fire",     ""},
    {"Ninetales",   "Fire",     ""},
    {"Jigglypuff",  "Normal",   "Fairy"},
    {"Wigglytuff",  "Normal",   "Fairy"},
    {"Zubat",       "Poison",   "Flying"},
    {"Golbat",      "Poison",   "Flying"},
    {"Oddish",      "Grass",    "Poison"},
    {"Gloom",       "Grass",    "Poison"},
    {"Vileplume",   "Grass",    "Poison"},
    {"Paras",       "Bug",      "Grass"},
    {"Parasect",    "Bug",      "Grass"},
    {"Venonat",     "Bug",      "Poison"},
    {"Venomoth",    "Bug",      "Poison"},
    {"Diglett",     "Ground",   ""},
    {"Dugtrio",     "Ground",   ""},
    {"Meowth",      "Normal",   ""},
    {"Persian",     "Normal",   ""},
    {"Psyduck",     "Water",    ""},
    {"Golduck",     "Water",    ""},
    {"Mankey",      "Fighting", ""},
    {"Primeape",    "Fighting", ""},
    {"Growlithe",   "Fire",     ""},
    {"Arcanine",    "Fire",     ""},
    {"Poliwag",     "Water",    ""},
    {"Poliwhirl",   "Water",    ""},
    {"Poliwrath",   "Water",    "Fighting"},
    {"Abra",        "Psychic",  ""},
    {"Kadabra",     "Psychic",  ""},
    {"Alakazam",    "Psychic",  ""},
    {"Machop",      "Fighting", ""},
    {"Machoke",     "Fighting", ""},
    {"Machamp",     "Fighting", ""},
    {"Bellsprout",  "Grass",    "Poison"},
    {"Weepinbell",  "Grass",    "Poison"},
    {"Victreebel",  "Grass",    "Poison"},
    {"Tentacool",   "Water",    "Poison"},
    {"Tentacruel",  "Water",    "Poison"},
    {"Geodude",     "Rock",     "Ground"},
    {"Graveler",    "Rock",     "Ground"},
    {"Golem",       "Rock",     "Ground"},
    {"Ponyta",      "Fire",     ""},
    {"Rapidash",    "Fire",     ""},
    {"Slowpoke",    "Water",    "Psychic"},
    {"Slowbro",     "Water",    "Psychic"},
    {"Magnemite",   "Electric", "Steel"},
    {"Magneton",    "Electric", "Steel"},
    {"Farfetchd",   "Normal",   "Flying"},
    {"Doduo",       "Normal",   "Flying"},
    {"Dodrio",      "Normal",   "Flying"},
    {"Seel",        "Water",    ""},
    {"Dewgong",     "Water",    "Ice"},
    {"Grimer",      "Poison",   ""},
    {"Muk",         "Poison",   ""},
    {"Shellder",    "Water",    ""},
    {"Cloyster",    "Water",    "Ice"},
    {"Gastly",      "Ghost",    "Poison"},
    {"Haunter",     "Ghost",    "Poison"},
    {"Gengar",      "Ghost",    "Poison"},
    {"Onix",        "Rock",     "Ground"},
    {"Drowzee",     "Psychic",  ""},
    {"Hypno",       "Psychic",  ""},
    {"Krabby",      "Water",    ""},
    {"Kingler",     "Water",    ""},
    {"Voltorb",     "Electric", ""},
    {"Electrode",   "Electric", ""},
    {"Exeggcute",   "Grass",    "Psychic"},
    {"Exeggutor",   "Grass",    "Psychic"},
    {"Cubone",      "Ground",   ""},
    {"Marowak",     "Ground",   ""},
    {"Hitmonlee",   "Fighting", ""},
    {"Hitmonchan",  "Fighting", ""},
    {"Lickitung",   "Normal",   ""},
    {"Koffing",     "Poison",   ""},
    {"Weezing",     "Poison",   ""},
    {"Rhyhorn",     "Ground",   "Rock"},
    {"Rhydon",      "Ground",   "Rock"},
    {"Chansey",     "Normal",   ""},
    {"Tangela",     "Grass",    ""},
    {"Kangaskhan",  "Normal",   ""},
    {"Horsea",      "Water",    ""},
    {"Seadra",      "Water",    ""},
    {"Goldeen",     "Water",    ""},
    {"Seaking",     "Water",    ""},
    {"Staryu",      "Water",    ""},
    {"Starmie",     "Water",    "Psychic"},
    {"Mr. Mime",    "Psychic",  "Fairy"},
    {"Scyther",     "Bug",      "Flying"},
    {"Jynx",        "Ice",      "Psychic"},
    {"Electabuzz",  "Electric", ""},
    {"Magmar",      "Fire",     ""},
    {"Pinsir",      "Bug",      ""},
    {"Tauros",      "Normal",   ""},
    {"Magikarp",    "Water",    ""},
    {"Gyarados",    "Water",    "Flying"},
    {"Lapras",      "Water",    "Ice"},
    {"Ditto",       "Normal",   ""},
    {"Eevee",       "Normal",   ""},
    {"Vaporeon",    "Water",    ""},
    {"Jolteon",     "Electric", ""},
    {"Flareon",     "Fire",     ""},
    {"Porygon",     "Normal",   ""},
    {"Omanyte",     "Rock",     "Water"},
    {"Omastar",     "Rock",     "Water"},
    {"Kabuto",      "Rock",     "Water"},
    {"Kabutops",    "Rock",     "Water"},
    {"Aerodactyl",  "Rock",     "Flying"},
    {"Snorlax",     "Normal",   ""},
    {"Articuno",    "Ice",      "Flying"},
    {"Zapdos",      "Electric", "Flying"},
    {"Moltres",     "Fire",     "Flying"},
    {"Dratini",     "Dragon",   ""},
    {"Dragonair",   "Dragon",   ""},
    {"Dragonite",   "Dragon",   "Flying"},
    {"Mewtwo",      "Psychic",  ""},
    {"Mew",         "Psychic",  ""},
};
static const uint8_t NUM_POKEMON = 151;

// 30-word curated subset — ASCII-folded German + English only (no Turkish since
// Adafruit GFX only covers ASCII 0x20-0x7E).
static const SplashGerman GERMAN[] = {
    {"eins",      "one"},
    {"zwei",      "two"},
    {"drei",      "three"},
    {"gut",       "good"},
    {"schlecht",  "bad"},
    {"gross",     "big"},
    {"klein",     "small"},
    {"neu",       "new"},
    {"alt",       "old"},
    {"schnell",   "fast"},
    {"langsam",   "slow"},
    {"schon",     "beautiful"},
    {"warm",      "warm"},
    {"kalt",      "cold"},
    {"heute",     "today"},
    {"morgen",    "tomorrow"},
    {"gestern",   "yesterday"},
    {"Haus",      "house"},
    {"Tisch",     "table"},
    {"Buch",      "book"},
    {"Wasser",    "water"},
    {"Feuer",     "fire"},
    {"Sonne",     "sun"},
    {"Mond",      "moon"},
    {"Hund",      "dog"},
    {"Katze",     "cat"},
    {"Baum",      "tree"},
    {"rot",       "red"},
    {"blau",      "blue"},
    {"gruen",     "green"},
};
static const uint8_t NUM_GERMAN = 30;
